"""add_missing_daily_log_columns

Revision ID: 1f97f4cde6fd
Revises: a1b2c3d4e5f6
Create Date: 2026-03-05 14:57:46.451938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f97f4cde6fd'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('junk_food', sa.Boolean(), nullable=True))
    op.add_column('daily_logs', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('daily_logs', sa.Column('bp_systolic', sa.Integer(), nullable=True))
    op.add_column('daily_logs', sa.Column('bp_diastolic', sa.Integer(), nullable=True))
    op.add_column('daily_logs', sa.Column('blood_sugar', sa.Integer(), nullable=True))
    op.add_column('daily_logs', sa.Column('heart_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_logs', 'heart_rate')
    op.drop_column('daily_logs', 'blood_sugar')
    op.drop_column('daily_logs', 'bp_diastolic')
    op.drop_column('daily_logs', 'bp_systolic')
    op.drop_column('daily_logs', 'weight')
    op.drop_column('daily_logs', 'junk_food')
    # ### end Alembic commands ###
