"""add_medicine_photo_url

Revision ID: f8d69c7e8214
Revises: 2386737817b8
Create Date: 2026-02-17 17:56:07.908212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d69c7e8214'
down_revision: Union[str, Sequence[str], None] = '2386737817b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('photo_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'photo_url')
    # ### end Alembic commands ###
