"""Add_Event_Time_Color

Revision ID: 3bc6fa2e0380
Revises: 572b723907c6
Create Date: 2026-02-15 00:45:26.028175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc6fa2e0380'
down_revision: Union[str, Sequence[str], None] = '572b723907c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
