"""Fix_Reminder_Time_To_String

Revision ID: d759cc7bff4e
Revises: 3bc6fa2e0380
Create Date: 2026-02-15 00:50:25.592774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd759cc7bff4e'
down_revision: Union[str, Sequence[str], None] = '3bc6fa2e0380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('reminder_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('reminder_time',
               existing_type=sa.String(length=10),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
